openapi: 3.0.3
info:
  title: Estate Customer Management API
  version: 1.0.0
  description: Endpoints for customers to view their assigned properties.

servers:
  - url: http://localhost:8080/api

paths:
  /customer/properties:
    get:
      summary: Fetch all properties assigned to the authenticated customer
      operationId: getCustomerProperties
      responses:
        '200':
          description: List of properties assigned to the customer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PropertyResponse'
        '401':
          description: Unauthorized

components:
  schemas:
    PropertyResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        address:
          type: string
        price:
          type: number
          format: double
        isNewConstruction:
          type: boolean
        agentId:
          type: integer
        customerId:
          type: integer